// Generated by Wrangler by running `wrangler types --config wrangler.jsonc --env-interface CloudflareEnv ./cloudflare-env.d.ts`

interface CloudflareEnv {
	CACHE_KV: KVNamespace;
	ENVIRONMENT: "development";
	R2_PUBLIC_URL: "https://storage-dev.yourdomain.com";
	R2_STORAGE: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
